name: Publish to Github Pages

on:
  schedule:
    - cron: "5 * * * *"
  push:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
  REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}

jobs:
  run:
    name: Publish JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc
      - name: Update JSON
        run: node dist/fetch.js

      - name: Check if data files were updated
        run: |
          if ! git diff --exit-code --name-only data-*.json; then
            echo "UPDATED=1" >> $GITHUB_ENV
          fi

      - name: Commit updated data files
        run: |
          echo "machine github.com login accesskey password ${{ secrets.TOKEN }}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          mkdir public
          cp data-*.json ./public
          cd public
          git pull remote gh-pages
          git add data-*.json
          git commit -m "update JSON"
          git push origin HEAD:gh-pages
