name: Publish to Github Pages

on:
  schedule:
    - cron: "5 * * * *"
  push:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
  REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}

jobs:
  run:
    name: Publish JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Clone data-files from gh-pages branch
        run:
          git clone https://github.com/Lenakh97/Nordic-strava-application
          --branch gh-pages --depth 1 data

      - name: Update JSON
        run: node dist/fetch.js

      - name: Summarize JSON
        run: node dist/summarize.js

      - name: Check if data files were updated
        working-directory: data
        run: |
          if ! git diff --exit-code; then
            echo "UPDATED=1" >> $GITHUB_ENV
          fi

      - name: Commit updated data files
        working-directory: data
        if: env.UPDATED == '1'
        run: |
          echo "machine github.com login accesskey password ${{ secrets.TOKEN }}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git add strava/data-*.json
          git add summary-*.json
          git commit -m "update JSON"
          git push
