name: Test and release

on:
  push:
  schedule:
    - cron: 0 1 * * *

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    name: "run code"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Run code
        run: node fetch.js

  publish:
    name: "Publish to github pages"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to github pages
      run: |
        git checkout -b gh-pages
        git config --global user.email "Lenaharaldseid@gmail.com"
        git config --global user.name "Lenakh97"
        mkdir public
        cp JSONObject.json ./public
        git add public/JSONObject.json
        git commit -m "update JSON"
        git push -f
      